Models/Basket.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Models
{
    public class Basket
    {
        public List<BasketLineItem> Items { get; set; } = new List<BasketLineItem>();

        public void AddItem (Books boo, int qty)
        {
            BasketLineItem line = Items
                .Where(b => b.Books.Category == boo.Category)
                .FirstOrDefault();

            if (line == null)
            {
                Items.Add(new BasketLineItem
                {
                    Books = boo,
                    Quantity = qty,

                });
            }
            else
            {
                line.Quantity += qty;
            }
        }
        public double CalculateTotal()
        {
            double sum = Items.Sum(x => x.Books.Price);

            return sum;
        }

    }

    public class BasketLineItem
    {
        public int LineID { get; set; }
        public Books Books { get; set; }
        public int Quantity { get; set; }

    }
}

Models/Books.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace BookStore.Models
{
    public class Books
    {
        [Key]
        [Required]
        public int BookId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public string Isbn { get; set; }
        public string Classification { get; set; }
        public string Category { get; set; }
        public int PageCount { get; set; }
        public double Price { get; set; }
    }
}

Models/BookstoreContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace BookStore.Models
{
    public class BookstoreContext : DbContext
    {
        public BookstoreContext()
        {
        }

        public BookstoreContext(DbContextOptions<BookstoreContext> options)
            : base(options)
        {
        }

        public DbSet<Books> Books { get; set; }

    }
}

Models/EFBookStoreRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Models
{
    public class EFBookStoreRepository : IBookStoreRepository
    {
        private BookstoreContext context {get; set; }

        public EFBookStoreRepository(BookstoreContext temp)
        {
            context = temp;
        }
        public IQueryable<Books> Books => context.Books;
    }
}

Models/IBookStoreRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Models
{
    public interface IBookStoreRepository
    {
        IQueryable<Books> Books { get; }
    }
}

Models/ViewModels/BooksViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Models.ViewModels
{
    public class BooksViewModel
    {
        public IQueryable<Books> Books { get; set; }
        public PageInfo PageInfo { get; set; }
    }
}

Models/ViewModels/PageInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Models.ViewModels
{
    public class PageInfo
    {
        public int TotalNumBooks { get; set; }
        public int BooksPerPage { get; set; }
        public int CurrentPage { get; set; }

        //Figure out how many pages we need
        public int TotalPages => (int) Math.Ceiling((double)TotalNumBooks / BooksPerPage);
    }
}

Components/TypesViewComponent.cs
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookStoreRepository repo { get; set; }

        public TypesViewComponent (IBookStoreRepository temp)
        {
            repo = temp; 
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["bookType"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

Controllers/HomeController.cs
using BookStore.Models;
using BookStore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Controllers
{
    public class HomeController : Controller
    {
        private IBookStoreRepository repo;

        //private BookstoreContext context { get; set; }

        public HomeController(IBookStoreRepository temp)
        {
            repo = temp;
        }

        public IActionResult Index(string bookType, int pageNum = 1)
        {
            int pageSize = 10;

            var x = new BooksViewModel
            {
                Books = repo.Books
                .Where(b => b.Category == bookType || bookType == null)
                .OrderBy(b => b.BookId)
                .Skip((pageNum - 1) * pageSize)
                .Take(pageSize),

                PageInfo = new PageInfo
                {
                    TotalNumBooks =
                        (bookType == null
                            ? repo.Books.Count()
                            : repo.Books.Where(x => x.Category == bookType).Count()),
                    BooksPerPage = pageSize,
                    CurrentPage = pageNum
                }
            };
            return View(x);
        }
    }
}


//public HomeController(BookstoreContext temp)
//{
//    context = temp;
//}
// using => lamba symbol is a short cut to the below commented out section 

Pages/Shop.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStore.Infrastructure;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookStore.Pages
{
    public class ShopModel : PageModel
    {
        private IBookStoreRepository repo { get; set; }

        public ShopModel (IBookStoreRepository temp)
        {
            repo = temp; 
        }

        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            basket = HttpContext.Session.GetJson<Basket>("basket") ?? new Basket();
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Books b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            basket = HttpContext.Session.GetJson<Basket>("basket") ?? new Basket();
            basket.AddItem(b, 1);

            HttpContext.Session.SetJson("basket", basket);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

Pages/Shop.cshtml
@page
@model BookStore.Pages.ShopModel
@{
}

<h2>Your Basket</h2>

<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
                
        </tr>
    </thead>
    <tbody>
        @foreach(var i in Model.basket.Items)
            {
                <tr>
                    <td>@i.Books.Category</td>
                    <td>@i.Quantity</td>
                    <td>25</td>
                    <td>@(i.Quantity * 25)</td>
                </tr>
            }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>

</table> 

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
</div>

Pages/_ShopLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        Bookstore
    </div>
   

    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>

Views/Home/Index.cshtml
@{
}
@model BooksViewModel



@foreach (Books b in Model.Books)
            {
                <partial name="ProjectSummary" model="b"/>
            }
<div page-blah="@Model.PageInfo" page-action="Index" page-class="btn"
     page-class-normal="btn-outline-dark" page-class-selected="btn-primary" page-classes-enabled="true"
     class="btn-group pull-right m-1"></div>

Views/Shared/Components/Types/Default.cshtml
@{
}

@model IEnumerable<string>

    <div class="d-grid gap-2">
    <a asp-controller="Home" asp-action="Index" asp-route-bookType="" asp-route-pageNum="1" class="btn btn-outline-secondary">Home</a>
    

    @foreach (string t in Model)
    {
        <a asp-controller="Home" asp-action="Index" asp-route-bookType="@t" asp-route-pageNum="1"
           class="btn @(ViewBag.SelectedType == t ? "btn-primary" :  "btn-outline-secondary")">@t</a>
    }
    </div>                   

Views/Shared/ProjectSummary.cshtml
@{
}

@model Books



    <div class="card card-outline-primary m-1 p-1">

        <div class="bg-light P-1">
            <h4>@Model.BookId</h4>

            <!--<span class="badge bg-info" style="float:right">

            </span>-->
        </div>

        <ul>
            <li>Title: @Model.Title</li>
            <li>Author: @Model.Author</li>
            <li>Publisher: @Model.Publisher</li>
            <li>ISBM: @Model.Isbn</li>
            <li>Classification: @Model.Classification</li>
            <li>Category: @Model.Category</li>
            <li>Number of Pages; @Model.PageCount</li>
            <li>Price: @Model.Price</li>
        </ul>
        <form method="post" asp-page="/Shop">

            <input type="hidden" asp-for="@Model.BookId" />
            <input type="hidden" name="returnURL" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

            <span class="card-text">
                <button type="submit" class="btn btn-success btn-sm float-end">Add to Cart</button>
            </span>

        </form>
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

        <div class="bg-dark text-white p-2">
            <span class="navbar-brand ml-2">The Bookstore</span>
        </div>
        <div class="row m-1 p-1">
            <div id="categories" class="col-3">
                <vc:types></vc:types>
            </div>

            <div class="col-9">
                @RenderBody()
            </div>
            </div>
</body>
</html>